package cashier.views;

import cashier.helpers.Popup;
import cashier.models.User;

public class Admin extends javax.swing.JFrame {

    private User currentUser;

    /**
     * Creates new form Admin
     */
    public Admin() {
    }

    public Admin(User user) {
        this.setLocationRelativeTo(null); // center the window
        initComponents();
        currentUser = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        windowTitle = new javax.swing.JLabel();
        manageUsersButton = new javax.swing.JButton();
        manageItemsButton = new javax.swing.JButton();
        menuKasirButton = new javax.swing.JButton();
        manageTransactionsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        windowTitle.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        windowTitle.setText("Daftar Menu");

        manageUsersButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        manageUsersButton.setText("Daftar User");
        manageUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersButtonActionPerformed(evt);
            }
        });

        manageItemsButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        manageItemsButton.setText("Daftar Makanan");
        manageItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageItemsButtonActionPerformed(evt);
            }
        });

        menuKasirButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        menuKasirButton.setText("Kasir");
        menuKasirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKasirButtonActionPerformed(evt);
            }
        });

        manageTransactionsButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        manageTransactionsButton.setText("Daftar Transaksi");
        manageTransactionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTransactionsButtonActionPerformed(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(manageItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageTransactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButton)
                    .addComponent(windowTitle)
                    .addComponent(manageUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(windowTitle)
                .addGap(18, 18, 18)
                .addComponent(manageItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(manageTransactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void manageUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersButtonActionPerformed
            Popup.<UserManager>open(new UserManager(this, currentUser), "Manajemen User");
            this.dispose();
	}//GEN-LAST:event_manageUsersButtonActionPerformed

    private void manageItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Popup.<MenuManager>open(new MenuManager(this, currentUser), "Manajemen Menu");
        this.dispose();
    }

	private void menuKasirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKasirButtonActionPerformed
            Popup.<Kasir>open(new Kasir(currentUser), "Halaman Kasir");
            this.dispose();
	}//GEN-LAST:event_menuKasirButtonActionPerformed

	private void manageTransactionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTransactionsButtonActionPerformed
            Popup.<TransactionManager>open(new TransactionManager(this, currentUser), "Manajemen Transaksi");
            this.dispose();
	}//GEN-LAST:event_manageTransactionsButtonActionPerformed

	private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordToggleActionPerformed
            Popup.<Login>open(new Login(), "Login Aplikasi Kasir");
            this.dispose();
	}//GEN-LAST:event_passwordToggleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton manageItemsButton;
    private javax.swing.JButton manageTransactionsButton;
    private javax.swing.JButton manageUsersButton;
    private javax.swing.JButton menuKasirButton;
    private javax.swing.JLabel windowTitle;
    // End of variables declaration//GEN-END:variables
}
